<?php declare(strict_types=1);

namespace AppBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190802164905 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE content_contribution (id INT AUTO_INCREMENT NOT NULL, role_id INT NOT NULL, person_id INT NOT NULL, content_id INT NOT NULL, note LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_EEBD12AAD60322AC (role_id), INDEX IDX_EEBD12AA217BBB47 (person_id), INDEX IDX_EEBD12AA84A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, feature_id INT DEFAULT NULL, content_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_C53D045F60E4B879 (feature_id), INDEX IDX_C53D045F84A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_url (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE place (id INT AUTO_INCREMENT NOT NULL, full_name VARCHAR(255) NOT NULL, sortable_name VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE print_source (id INT AUTO_INCREMENT NOT NULL, place_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_534D01C1DA6A219 (place_id), FULLTEXT INDEX IDX_534D01C1EA750E8 (label), FULLTEXT INDEX IDX_534D01C16DE44026 (description), FULLTEXT INDEX IDX_534D01C1EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_534D01C15E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manuscript_role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_CC99338FEA750E8 (label), FULLTEXT INDEX IDX_CC99338F6DE44026 (description), FULLTEXT INDEX IDX_CC99338FEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_CC99338F5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feature (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_1FD77566EA750E8 (label), FULLTEXT INDEX IDX_1FD775666DE44026 (description), FULLTEXT INDEX IDX_1FD77566EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_1FD775665E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_file (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE circa_date (id INT AUTO_INCREMENT NOT NULL, value VARCHAR(255) NOT NULL, start INT DEFAULT NULL, start_circa TINYINT(1) DEFAULT \'0\' NOT NULL, end INT DEFAULT NULL, end_circa TINYINT(1) DEFAULT \'0\' NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE theme (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_9775E708EA750E8 (label), FULLTEXT INDEX IDX_9775E7086DE44026 (description), FULLTEXT INDEX IDX_9775E708EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_9775E7085E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, birth_date_id INT DEFAULT NULL, death_date_id INT DEFAULT NULL, birth_place_id INT DEFAULT NULL, death_place_id INT DEFAULT NULL, full_name VARCHAR(255) NOT NULL, variant_names LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', sortable_name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_34DCD176C38A9A1D (birth_date_id), UNIQUE INDEX UNIQ_34DCD1765171AA8B (death_date_id), INDEX IDX_34DCD176B4BB6BBC (birth_place_id), INDEX IDX_34DCD176AD45A6FD (death_place_id), FULLTEXT INDEX person_ft (full_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content (id INT AUTO_INCREMENT NOT NULL, manuscript_id INT NOT NULL, print_source_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, transcription LONGTEXT DEFAULT NULL, context LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_FEC530A9A05723D9 (manuscript_id), INDEX IDX_FEC530A9E75A3578 (print_source_id), FULLTEXT INDEX content_ft (title, transcription), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manuscript_contribution (id INT AUTO_INCREMENT NOT NULL, person_id INT NOT NULL, role_id INT NOT NULL, manuscript_id INT NOT NULL, note LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_27AC307B217BBB47 (person_id), INDEX IDX_27AC307BD60322AC (role_id), INDEX IDX_27AC307BA05723D9 (manuscript_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE content_role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_9A0B67AFEA750E8 (label), FULLTEXT INDEX IDX_9A0B67AF6DE44026 (description), FULLTEXT INDEX IDX_9A0B67AFEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_9A0B67AF5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE period (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_C5B81ECEEA750E8 (label), FULLTEXT INDEX IDX_C5B81ECE6DE44026 (description), FULLTEXT INDEX IDX_C5B81ECEEA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_C5B81ECE5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE archive_source (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) NOT NULL, label VARCHAR(120) NOT NULL, description LONGTEXT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, FULLTEXT INDEX IDX_A28F6B66EA750E8 (label), FULLTEXT INDEX IDX_A28F6B666DE44026 (description), FULLTEXT INDEX IDX_A28F6B66EA750E86DE44026 (label, description), UNIQUE INDEX UNIQ_A28F6B665E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manuscript (id INT AUTO_INCREMENT NOT NULL, place_id INT DEFAULT NULL, period_id INT DEFAULT NULL, archive_source_id INT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, bibliography LONGTEXT NOT NULL, blank_page_count INT NOT NULL, filled_page_count INT NOT NULL, item_count INT NOT NULL, poem_count INT NOT NULL, additional_genres LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', call_number VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_5AF919CDDA6A219 (place_id), INDEX IDX_5AF919CDEC8B7ADE (period_id), INDEX IDX_5AF919CDD1155EDD (archive_source_id), FULLTEXT INDEX manuscript_ft (title, description), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manuscript_print_source (manuscript_id INT NOT NULL, print_source_id INT NOT NULL, INDEX IDX_9ED42FAFA05723D9 (manuscript_id), INDEX IDX_9ED42FAFE75A3578 (print_source_id), PRIMARY KEY(manuscript_id, print_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manuscript_theme (manuscript_id INT NOT NULL, theme_id INT NOT NULL, INDEX IDX_478E0146A05723D9 (manuscript_id), INDEX IDX_478E014659027487 (theme_id), PRIMARY KEY(manuscript_id, theme_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manuscript_feature (id INT AUTO_INCREMENT NOT NULL, feature_id INT NOT NULL, manuscript_id INT NOT NULL, note LONGTEXT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_3844805B60E4B879 (feature_id), INDEX IDX_3844805BA05723D9 (manuscript_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nines_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', fullname VARCHAR(255) DEFAULT NULL, institution VARCHAR(255) DEFAULT NULL, data LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_5BA994A192FC23A8 (username_canonical), UNIQUE INDEX UNIQ_5BA994A1A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_5BA994A1C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wbnt_dfgb_test (id INT AUTO_INCREMENT NOT NULL, testrelated_id INT DEFAULT NULL, name VARCHAR(60) DEFAULT NULL, INDEX IDX_A86F10518E63F6D6 (testrelated_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wbnt_dfgb_testrelated (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE content_contribution ADD CONSTRAINT FK_EEBD12AAD60322AC FOREIGN KEY (role_id) REFERENCES content_role (id)');
        $this->addSql('ALTER TABLE content_contribution ADD CONSTRAINT FK_EEBD12AA217BBB47 FOREIGN KEY (person_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE content_contribution ADD CONSTRAINT FK_EEBD12AA84A0A3ED FOREIGN KEY (content_id) REFERENCES content (id)');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F60E4B879 FOREIGN KEY (feature_id) REFERENCES feature (id)');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F84A0A3ED FOREIGN KEY (content_id) REFERENCES content (id)');
        $this->addSql('ALTER TABLE image_url ADD CONSTRAINT FK_AC9C95FDBF396750 FOREIGN KEY (id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE print_source ADD CONSTRAINT FK_534D01C1DA6A219 FOREIGN KEY (place_id) REFERENCES place (id)');
        $this->addSql('ALTER TABLE image_file ADD CONSTRAINT FK_7EA5DC8EBF396750 FOREIGN KEY (id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176C38A9A1D FOREIGN KEY (birth_date_id) REFERENCES circa_date (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1765171AA8B FOREIGN KEY (death_date_id) REFERENCES circa_date (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176B4BB6BBC FOREIGN KEY (birth_place_id) REFERENCES place (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176AD45A6FD FOREIGN KEY (death_place_id) REFERENCES place (id)');
        $this->addSql('ALTER TABLE content ADD CONSTRAINT FK_FEC530A9A05723D9 FOREIGN KEY (manuscript_id) REFERENCES manuscript (id)');
        $this->addSql('ALTER TABLE content ADD CONSTRAINT FK_FEC530A9E75A3578 FOREIGN KEY (print_source_id) REFERENCES print_source (id)');
        $this->addSql('ALTER TABLE manuscript_contribution ADD CONSTRAINT FK_27AC307B217BBB47 FOREIGN KEY (person_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE manuscript_contribution ADD CONSTRAINT FK_27AC307BD60322AC FOREIGN KEY (role_id) REFERENCES manuscript_role (id)');
        $this->addSql('ALTER TABLE manuscript_contribution ADD CONSTRAINT FK_27AC307BA05723D9 FOREIGN KEY (manuscript_id) REFERENCES manuscript (id)');
        $this->addSql('ALTER TABLE manuscript ADD CONSTRAINT FK_5AF919CDDA6A219 FOREIGN KEY (place_id) REFERENCES place (id)');
        $this->addSql('ALTER TABLE manuscript ADD CONSTRAINT FK_5AF919CDEC8B7ADE FOREIGN KEY (period_id) REFERENCES period (id)');
        $this->addSql('ALTER TABLE manuscript ADD CONSTRAINT FK_5AF919CDD1155EDD FOREIGN KEY (archive_source_id) REFERENCES archive_source (id)');
        $this->addSql('ALTER TABLE manuscript_print_source ADD CONSTRAINT FK_9ED42FAFA05723D9 FOREIGN KEY (manuscript_id) REFERENCES manuscript (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manuscript_print_source ADD CONSTRAINT FK_9ED42FAFE75A3578 FOREIGN KEY (print_source_id) REFERENCES print_source (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manuscript_theme ADD CONSTRAINT FK_478E0146A05723D9 FOREIGN KEY (manuscript_id) REFERENCES manuscript (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manuscript_theme ADD CONSTRAINT FK_478E014659027487 FOREIGN KEY (theme_id) REFERENCES theme (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manuscript_feature ADD CONSTRAINT FK_3844805B60E4B879 FOREIGN KEY (feature_id) REFERENCES feature (id)');
        $this->addSql('ALTER TABLE manuscript_feature ADD CONSTRAINT FK_3844805BA05723D9 FOREIGN KEY (manuscript_id) REFERENCES manuscript (id)');
        $this->addSql('ALTER TABLE wbnt_dfgb_test ADD CONSTRAINT FK_A86F10518E63F6D6 FOREIGN KEY (testrelated_id) REFERENCES wbnt_dfgb_testrelated (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema) : void
    {
    }
}
