<?php

namespace AppBundle\Repository;

/**
 * AbstractSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
