<?php

namespace AppBundle\Repository;

/**
 * ArchiveSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
