<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CircaDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircaDateRepository extends EntityRepository
{

}
