<?php

namespace AppBundle\Repository;

/**
 * CircaDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircaDateRepository extends \Doctrine\ORM\EntityRepository
{
}
