<?php

namespace AppBundle\Repository;

/**
 * ContentPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
