<?php

namespace AppBundle\Repository;

/**
 * ContentContributionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentContributionRepository extends \Doctrine\ORM\EntityRepository {
}
