<?php

namespace AppBundle\Repository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->where("e.title LIKE :q");
        $qb->orWhere("e.firstLine like :q");
        $qb->orderBy('e.title');
        $qb->setParameter('q', "%{$q}%");

        return $qb->getQuery()->execute();
    }

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->where("MATCH (e.title, e.firstLine, e.transcription) AGAINST(:q BOOLEAN) > 0");
        $qb->setParameter('q', $q);

        return $qb->getQuery();
    }

}
