<?php

namespace AppBundle\Repository;

/**
 * ContentRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
