<?php

namespace AppBundle\Repository;

/**
 * ImageUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
