<?php

namespace AppBundle\Repository;

/**
 * ManuscriptContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptContributionRepository extends \Doctrine\ORM\EntityRepository
{
}
