<?php

namespace AppBundle\Repository;

/**
 * ManuscriptPersonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptPersonRepository extends \Doctrine\ORM\EntityRepository {
}
