<?php

namespace AppBundle\Repository;

/**
 * ManuscriptFeatureRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptFeatureRepository extends \Doctrine\ORM\EntityRepository {
}
