<?php

namespace AppBundle\Repository;

/**
 * ManuscriptRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptRepository extends \Doctrine\ORM\EntityRepository {
    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.title LIKE :q');
        $qb->orWhere('e.callNumber like :q');
        $qb->orderBy('e.title');
        $qb->setParameter('q', "%{$q}%");

        return $qb->getQuery()->execute();
    }

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.callNumber LIKE :q');
        $qb->orWhere('e.title LIKE :q');
        $qb->orderBy('e.callNumber', 'ASC');
        $qb->setParameter('q', "%{$q}%");

        return $qb->getQuery();
    }
}
