<?php

namespace AppBundle\Repository;

/**
 * ManuscriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptRepository extends \Doctrine\ORM\EntityRepository
{
}
