<?php

namespace AppBundle\Repository;

/**
 * ManuscriptContentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptContentRepository extends \Doctrine\ORM\EntityRepository {
}
