<?php

namespace AppBundle\Repository;

/**
 * ManuscriptRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
