<?php

namespace AppBundle\Repository;

use Nines\UtilBundle\Repository\TermRepository;

/**
 * PeriodRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends TermRepository {
}
