<?php

namespace AppBundle\Repository;

/**
 * PrintSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
