<?php

declare(strict_types=1);

namespace App\Repository;

use Nines\UtilBundle\Repository\TermRepository;

/**
 * AbstractSourceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractSourceRepository extends TermRepository {
}
