<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Manuscript;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Persistence\ManagerRegistry;
use Traversable;

/**
 * ManuscriptRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptRepository extends ServiceEntityRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, Manuscript::class);
    }

    public function indexQuery() {
        $qb = $this->createQueryBuilder('e');
        $qb->select('e');

        return $qb;
    }

    public function typeaheadQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->where('e.title LIKE :q');
        $qb->orWhere('e.callNumber like :q');
        $qb->orderBy('e.title');
        $qb->setParameter('q', "%{$q}%");

        return $qb->getQuery();
    }

    public function searchQuery($q = null, $untitled = null) {
        $qb = $this->createQueryBuilder('e');
        $matches = [];
        if ($q && preg_match('/^\s*"(.*?)"\s*$/u', (string) $q, $matches)) {
            $qb->where('e.callNumber LIKE :q');
            $qb->orWhere('e.title like :q');
            $qb->setParameter('q', "%{$matches[1]}%");
        } else {
            if ($q) {
                $qb->where('MATCH(e.callNumber, e.description, e.format) AGAINST (:q BOOLEAN) > 0.0');
                $qb->setParameter('q', $q);
            }
        }
        if ('false' === $untitled) {
            $qb->andWhere('e.untitled = 0');
        }
        $qb->orderBy('e.callNumber', 'ASC');

        return $qb;
    }

    public function getSortedQuery($qb, $sort) {
        if ( ! $sort) {
            return $qb->orderBy('e.callNumber', 'ASC');
        }

        switch ($sort) {
            case 'callNumber_asc':
                return $qb->orderBy('e.callNumber', 'ASC');

            case 'callNumber_desc':
                $qb->orderBy('e.callNumber', 'DESC');

                return $qb->getQuery();

            case 'title_asc':
                return self::sortByTitles($qb, 'ASC');

            case 'title_desc':
                return self::sortByTitles($qb, 'DESC');

            case 'periods_asc':
                return self::sortByPeriods($qb, 'ASC');

            case 'periods_desc':
                return self::sortByPeriods($qb, 'DESC');

            default:
                $qb->orderBy('e.callNumber', 'ASC');

                return $qb->getQuery();
        }
    }

    public function sortByPeriods($qb, $dir = 'ASC') {
        $results = $qb->getQuery()->getResult();
        uasort($results, function ($a, $b) use ($dir) {
            $ay = $a->getEarliestYear();
            $by = $b->getEarliestYear();
            if (0 === $ay) {
                return 1;
            }
            if (0 === $by) {
                return -1;
            }
            if ($ay === $by) {
                if ($a->getLatestYear() > $b->getLatestYear()) {
                    return 1;
                }
            }
            if ('ASC' === $dir) {
                return $ay <=> $by;
            }

            return $by <=> $ay;
        });

        return $results;
    }

    public function sortByTitles($qb, $dir = 'ASC') {
        $result = $qb->getQuery()->getResult();
        $rex = '/^(([[:punct:]]|((a|the)\\s))+)/i';
        uasort($result, function ($a, $b) use ($rex, $dir) {
            if ($a->getUntitled()) {
                return 1;
            }
            if ($b->getUntitled()) {
                return -1;
            }
            $at = preg_replace($rex, '', mb_strtolower((string) $a->getTitle()));
            $bt = preg_replace($rex, '', mb_strtolower((string) $b->getTitle()));
            if ('ASC' === $dir) {
                return strcmp($at, $bt);
            }

            return strcmp($bt, $at);
        });

        return $result;
    }

    public function getActiveFilters($form) {
        $active = [];
        if ($form->getData()) {
            foreach ($form->getData() as $key => $value) {
                if (null === $value) {
                    continue;
                }
                if (is_array($value)) {
                    $flat = self::array_flatten($value);
                    if (reset($flat) instanceof ArrayCollection) {
                        $values = reset($flat);
                        if (count($values) > 0) {
                            $active[$key] = $values;
                        }
                    }

                    continue;
                }
                if ($value instanceof Traversable) {
                    if (count($value) > 0) {
                        $active[$key] = $value->toArray();
                    }

                    continue;
                }
                if (is_string($value)) {
                    $active[$key] = 'y' === $value ? 'True' : 'False';

                    continue;
                }
                $active[$key] = [$value];
            }
        }

        return $active;
    }

    public function array_flatten($array) {
        if ( ! is_array($array)) {
            return false;
        }
        $result = [];
        foreach ($array as $key => $value) {
            if (is_array($value)) {
                $result = array_merge($result, self::array_flatten($value));
            } else {
                $result = array_merge($result, [$key => $value]);
            }
        }

        return $result;
    }
}
