<?php

declare(strict_types=1);

/*
 * (c) 2021 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\Repository;

use App\Entity\PrintSource;
use Doctrine\Persistence\ManagerRegistry;

/**
 * PrintSourceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintSourceRepository extends AbstractSourceRepository {
    public function __construct(ManagerRegistry $registry) {
        parent::__construct($registry, PrintSource::class);
    }

    public function searchQuery($q) {
        $qb = $this->createQueryBuilder('print_source');
        $qb->innerJoin('print_source.regions', 'region');
        $qb->where('MATCH(print_source.label, print_source.description) AGAINST (:q BOOLEAN) > 0.0');
        $qb->orWhere('MATCH(region.name) AGAINST (:q BOOLEAN) > 0.0');
        $qb->setParameter('q', $q);

        return $qb->getQuery()->execute();
    }
}
