<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\Content;
use DateTimeImmutable;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class ContentFixtures extends Fixture implements DependentFixtureInterface {
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getDependencies() {
        return [
            ManuscriptFixtures::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $manager->getClassMetadata(Content::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new Content();
        $item1->setFirstLine('To a Butterfly');
        $item1->setTranscription("<p>I've watched you now a full half-hour;<br />Self-poised upon that yellow flower<br />And, little Butterfly! indeed<br />I know not if you sleep or feed.<br />How motionless!--not frozen seas<br />More motionless! and then<br />What joy awaits you, when the breeze<br />Hath found you out among the trees,<br />And calls you forth again!</p>
<p>This plot of orchard-ground is ours;<br />My trees they are, my Sister's flowers;<br />Here rest your wings when they are weary;<br />Here lodge as in a sanctuary!<br />Come often to us, fear no wrong;<br />Sit near us on the bough!<br />We'll talk of sunshine and of song,<br />And summer days, when we were young;<br />Sweet childish days, that were as long<br />As twenty days are now.</p>
<hr />
<p>STAY near me--do not take thy flight!<br />A little longer stay in sight!<br />Much converse do I find in thee,<br />Historian of my infancy!<br />Float near me; do not yet depart!<br />Dead times revive in thee:<br />Thou bring'st, gay creature as thou art!<br />A solemn image to my heart,<br />My father's family!</p>
<p>Oh! pleasant, pleasant were the days,<br />The time, when, in our childish plays,<br />My sister Emmeline and I<br />Together chased the butterfly!<br />A very hunter did I rush<br />Upon the prey:--with leaps and springs<br />I followed on from brake to bush;<br />But she, God love her, feared to brush<br />The dust from off its wings.</p>
<p>&nbsp;</p>");
        $item1->setDescription("<p>Marge's handwriting, with additional note.</p>");
        $item1->setCreated(new DateTimeImmutable('2019-07-29 22:41:59'));
        $item1->setUpdated(new DateTimeImmutable('2019-07-29 22:41:59'));
        $this->addReference('_reference_Content1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
