<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\ContentContribution;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class ContentContributionFixtures extends Fixture implements DependentFixtureInterface
{
    /**
     * Set loading order.
     */
    public function getDependencies() {
        return [
            ContentRoleFixtures::class,
            PersonFixtures::class,
            ContentFixtures::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $manager->getClassMetadata(ContentContribution::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new ContentContribution();
        $item1->setNote('<p>Attributed on the page as "WORDSWORTH!"</p>');
        $item1->setRole($this->getReference('_reference_ContentRole1'));
        $item1->setPerson($this->getReference('_reference_Person2'));
        $item1->setContent($this->getReference('_reference_Content1'));
        $this->addReference('_reference_ContentContribution1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
