<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\ManuscriptFeature;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class ManuscriptFeatureFixtures extends Fixture implements DependentFixtureInterface {
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getDependencies() {
        return [
            ManuscriptFixtures::class,
            FeatureFixtures::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $manager->getClassMetadata(ManuscriptFeature::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new ManuscriptFeature();
        $item1->setNote('<p>Professionally bound.</p>');
        $item1->setFeature($this->getReference('_reference_Feature1'));
        $item1->setManuscript($this->getReference('_reference_Manuscript1'));
        $item1->setCreated(new \DateTime('2019-07-29 22:49:10'));
        $item1->setUpdated(new \DateTime('2019-07-29 22:49:10'));
        $this->addReference('_reference_ManuscriptFeature1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
