<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\Manuscript;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class ManuscriptFixtures extends Fixture implements DependentFixtureInterface {
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getDependencies() {
        return [
            RegionFixtures::class,
            PeriodFixtures::class,
            ArchiveFixtures::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $manager->getClassMetadata(Manuscript::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new Manuscript();
        $item1->setUntitled(false);
        $item1->setTitle("Marge's favourite poems");
        $item1->setCallNumber('SLC 123');
        $item1->setDescription('<p>Found hidden in an attic by Lisa, who later added new content.</p>');
        $item1->setBlankPageCount(23);
        $item1->setFilledPageCount(41);
        $item1->setItemCount(25);
        $item1->setPoemCount(23);
        $item1->setAdditionalGenres(unserialize('a:0:{}'));
        $item1->addRegion($this->getReference('_reference_Region1'));
        $item1->addPeriod($this->getReference('_reference_Period1'));
        $item1->setArchive($this->getReference('_reference_Archive1'));
        $item1->setCreated(new \DateTime('2019-07-29 22:35:10'));
        $item1->setUpdated(new \DateTime('2019-07-29 22:35:10'));
        $this->addReference('_reference_Manuscript1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
