<?php

declare(strict_types=1);

/*
 * (c) 2020 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\ManuscriptRole;
use DateTimeImmutable;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class ManuscriptRoleFixtures extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $manager->getClassMetadata(ManuscriptRole::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new ManuscriptRole();
        $item1->setCreated(new DateTimeImmutable('2019-07-29 22:13:01'));
        $item1->setUpdated(new DateTimeImmutable('2019-07-29 22:13:01'));
        $item1->setName('primary_compiler');
        $item1->setLabel('Primary Compiler');
        $item1->setDescription('<p>The person most responsible for collecting the content in a manuscript.</p>');
        $this->addReference('_reference_ManuscriptRole1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
