<?php

declare(strict_types=1);

/*
 * (c) 2021 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\DataFixtures;

use App\Entity\Period;
use DateTimeImmutable;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\Persistence\ObjectManager;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class PeriodFixtures extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) : void {
        $manager->getClassMetadata(Period::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new Period();
        $item1->setCreated(new DateTimeImmutable('2019-07-29 22:17:32'));
        $item1->setUpdated(new DateTimeImmutable('2019-07-29 22:17:32'));
        $item1->setName('1700');
        $item1->setLabel('1700-1729');
        $item1->setDescription('<p>It was a very George II sort of time.</p>');
        $this->addReference('_reference_Period1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
