<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\PrintSource;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadPrintSource extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(PrintSource::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new PrintSource();
        $item1->setPlace($this->getReference('_reference_Place1'));
        $item1->setCreated(new \DateTime("2019-07-29 22:19:33"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:19:33"));
        $item1->setName("sgm");
        $item1->setLabel("Springfield Gentleman's Magazine");
        $item1->setDescription("<p>A fictious magazine in Springfield.</p>");
        $this->addReference('_reference_PrintSource1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
