<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ManuscriptRole;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadManuscriptRole extends Fixture {
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ManuscriptRole::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ManuscriptRole();
        $item1->setCreated(new \DateTime("2019-07-29 22:13:01"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:13:01"));
        $item1->setName("primary_compiler");
        $item1->setLabel("Primary Compiler");
        $item1->setDescription("<p>The person most responsible for collecting the content in a manuscript.</p>");
        $this->addReference('_reference_ManuscriptRole1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
