<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Manuscript;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadManuscript extends Fixture implements DependentFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getDependencies()
    {
        return array(
            LoadPlace::class,
            LoadPeriod::class,
            LoadArchiveSource::class,
        );
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Manuscript::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Manuscript();
        $item1->setUntitled(false);
        $item1->setTitle("Marge's favourite poems");
        $item1->setDescription("<p>Found hidden in an attic by Lisa, who later added new content.</p>");
        $item1->setBlankPageCount(23);
        $item1->setFilledPageCount(41);
        $item1->setItemCount(25);
        $item1->setPoemCount(23);
        $item1->setAdditionalGenres(unserialize('a:0:{}'));
        $item1->setPlace($this->getReference('_reference_Place1'));
        $item1->setPeriod($this->getReference('_reference_Period1'));
        $item1->setArchiveSource($this->getReference('_reference_ArchiveSource1'));
        $item1->setCreated(new \DateTime("2019-07-29 22:35:10"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:35:10"));
        $this->addReference('_reference_Manuscript1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
