<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Feature;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class LoadFeature extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Feature::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new Feature();
        $item1->setCreated(new \DateTime('2019-07-29 22:10:36'));
        $item1->setUpdated(new \DateTime('2019-07-29 22:10:36'));
        $item1->setName('glue_binding');
        $item1->setLabel('Glue Binding');
        $item1->setDescription('<p>The binding is glue holding the pages to a spine.</p>');
        $this->addReference('_reference_Feature1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
