<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ManuscriptFeature;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadManuscriptFeature extends Fixture implements DependentFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getDependencies()
    {
        return array(
            LoadManuscript::class,
            LoadFeature::class,
        );
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ManuscriptFeature::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ManuscriptFeature();
        $item1->setNote("<p>Professionally bound.</p>");
        $item1->setFeature($this->getReference('_reference_Feature1'));
        $item1->setManuscript($this->getReference('_reference_Manuscript1'));
        $item1->setCreated(new \DateTime("2019-07-29 22:49:10"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:49:10"));
        $this->addReference('_reference_ManuscriptFeature1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
