<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ManuscriptContribution;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityManuscriptContribution extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 4;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ManuscriptContribution::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ManuscriptContribution();
        $item1->setNote("<p>\"Property of M Simpson\" handwritten on the front page with date \"Summer '75\"</p>");
        $item1->setPerson($this->getReference('_reference_AppBundleEntityPerson1'));
        $item1->setRole($this->getReference('_reference_AppBundleEntityManuscriptRole1'));
        $item1->setManuscript($this->getReference('_reference_AppBundleEntityManuscript1'));
        $item1->setCreated(new \DateTime("2019-07-29 22:50:42"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:50:42"));
        $this->addReference('_reference_AppBundleEntityManuscriptContribution1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
