<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ManuscriptFeature;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityManuscriptFeature extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 4;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ManuscriptFeature::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ManuscriptFeature();
        $item1->setNote("<p>Professionally bound.</p>");
        $item1->setFeature($this->getReference('_reference_AppBundleEntityFeature1'));
        $item1->setManuscript($this->getReference('_reference_AppBundleEntityManuscript1'));
        $item1->setCreated(new \DateTime("2019-07-29 22:49:10"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:49:10"));
        $this->addReference('_reference_AppBundleEntityManuscriptFeature1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
