<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ContentContribution;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadContentContribution extends Fixture implements DependentFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getDependencies()
    {
        return array(
            LoadContentRole::class,
            LoadPerson::class,
            LoadContent::class,
        );
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ContentContribution::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ContentContribution();
        $item1->setNote("<p>Attributed on the page as \"WORDSWORTH!\"</p>");
        $item1->setRole($this->getReference('_reference_ContentRole1'));
        $item1->setPerson($this->getReference('_reference_Person2'));
        $item1->setContent($this->getReference('_reference_Content1'));
        $item1->setCreated(new \DateTime("2019-07-29 22:47:23"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:47:23"));
        $this->addReference('_reference_ContentContribution1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
