<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Theme;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadTheme extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Theme::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Theme();
        $item1->setCreated(new \DateTime("2019-07-29 22:25:27"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:25:27"));
        $item1->setName("butterflies");
        $item1->setLabel("Butterflies");
        $item1->setDescription("<p>Butterflies, leopodoptra, etc.</p>");
        $this->addReference('_reference_Theme1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
