<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ArchiveSource;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadArchiveSource extends Fixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ArchiveSource::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ArchiveSource();
        $item1->setCreated(new \DateTime("2019-07-29 21:18:59"));
        $item1->setUpdated(new \DateTime("2019-07-29 21:18:59"));
        $item1->setName("springfield_pl");
        $item1->setLabel("Springfield Public Library");
        $item1->setDescription("<p>Like on the Simpsons.</p>");
        $this->addReference('_reference_ArchiveSource1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
