<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Archive;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class LoadArchive extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Archive::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new Archive();
        $item1->setCreated(new \DateTime('2019-07-29 21:18:59'));
        $item1->setUpdated(new \DateTime('2019-07-29 21:18:59'));
        $item1->setName('springfield_pl');
        $item1->setLabel('Springfield Public Library');
        $item1->setDescription('<p>Like on the Simpsons.</p>');
        $this->addReference('_reference_Archive1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
