<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ContentRole;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityContentRole extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ContentRole::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ContentRole();
        $item1->setCreated(new \DateTime("2019-07-29 22:08:59"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:08:59"));
        $item1->setName("author");
        $item1->setLabel("Author");
        $item1->setDescription("<p>The person most responsible for the creation of a work.</p>");
        $this->addReference('_reference_AppBundleEntityContentRole1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
