<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\Manuscript;
use AppBundle\Entity\ManuscriptContent;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class LoadManuscriptContent extends Fixture implements DependentFixtureInterface {
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getDependencies() {
        return array(
            LoadManuscript::class,
            LoadContent::class,
            LoadPrintSource::class,
        );
    }

    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(Manuscript::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new ManuscriptContent();
        $item1->setContent($this->getReference('_reference_Content1'));
        $item1->setManuscript($this->getReference('_reference_Manuscript1'));
        $item1->setContext('On a page');
        $item1->setPrintSource($this->getReference('_reference_PrintSource1'));
        $this->addReference('_reference_ManuscriptContent1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
