<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Place;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadPlace extends Fixture{
    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Place::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Place();
        $item1->setFullName("Springfield IL");
        $item1->setSortableName("springfield il");
        $item1->setCreated(new \DateTime("2019-07-29 22:18:40"));
        $item1->setUpdated(new \DateTime("2019-07-29 22:18:40"));
        $this->addReference('_reference_Place1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
