<?php

namespace AppBundle\DataFixtures\ORM;

use AppBundle\Entity\ManuscriptRole;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 */
class LoadManuscriptRole extends Fixture {
    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager) {
        $manager->getClassMetadata(ManuscriptRole::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new ManuscriptRole();
        $item1->setCreated(new \DateTime('2019-07-29 22:13:01'));
        $item1->setUpdated(new \DateTime('2019-07-29 22:13:01'));
        $item1->setName('primary_compiler');
        $item1->setLabel('Primary Compiler');
        $item1->setDescription('<p>The person most responsible for collecting the content in a manuscript.</p>');
        $this->addReference('_reference_ManuscriptRole1', $item1);
        $manager->persist($item1);

        $manager->flush();
    }
}
